name: 🎯 New Integration
description: Create a new integration implementation
title: "🎯 Integration: [Service Name] Implementation"
labels: ["integration: new"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose a new integration!

  - type: input
    id: service-name
    attributes:
      label: Service Name
      description: What service are we integrating?
      placeholder: "e.g., Auth0"
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: Integration Purpose
      description: What is the main purpose of this integration?
      placeholder: "e.g., Implement authentication and user management capabilities"
    validations:
      required: true

  - type: textarea
    id: key-features
    attributes:
      label: Key Features
      description: List the main features to be implemented
      placeholder: |
        - User authentication flows
        - Token management
        - User management operations
        - Role and permission handling
    validations:
      required: true

  - type: textarea
    id: technical-requirements
    attributes:
      label: Technical Requirements
      description: List the technical requirements for this integration
      value: |
        - Follow Polvo's standard async interface
        - Implement comprehensive error handling
        - Add proper rate limiting
        - Include type definitions
        - Write integration tests
        - Add documentation
    validations:
      required: true

  - type: textarea
    id: success-criteria
    attributes:
      label: Success Criteria
      description: What defines this integration as complete?
      value: |
        - All core operations supported
        - 90%+ test coverage
        - Documentation complete
        - Example implementation added
        - Security review completed
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What is the priority level for this integration?
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: dropdown
    id: milestone
    attributes:
      label: Target Milestone
      description: When should this integration be completed?
      options:
        - "Q1 2024: Foundation"
        - "Q2 2024: Expansion"
        - "Q3 2024: Enterprise Features"
        - "Q4 2024: Community & Scale"
    validations:
      required: true
