name: 🔄 Core Feature
description: Propose a new core framework feature
title: "🔄 Core: [Feature Name]"
labels: ["core: feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose a new core feature!

  - type: input
    id: feature-name
    attributes:
      label: Feature Name
      description: What is the name of this core feature?
      placeholder: "e.g., Standardize Response Format"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear description of the core feature
      placeholder: "e.g., Create and implement a standardized response format across all integrations"
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: Goals
      description: What are the main goals of this feature?
      placeholder: |
        - Consistent error handling
        - Standardized pagination
        - Uniform metadata structure
    validations:
      required: true

  - type: textarea
    id: implementation-requirements
    attributes:
      label: Implementation Requirements
      description: List the technical requirements for implementation
      placeholder: |
        - Define response interface
        - Create response utilities
        - Update existing integrations
        - Add validation
    validations:
      required: true

  - type: textarea
    id: success-criteria
    attributes:
      label: Success Criteria
      description: What defines this feature as complete?
      placeholder: |
        - All integrations using new format
        - Documentation updated
        - Migration guide written
        - Tests passing
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What is the priority level for this feature?
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: dropdown
    id: milestone
    attributes:
      label: Target Milestone
      description: When should this feature be completed?
      options:
        - "Q1 2024: Foundation"
        - "Q2 2024: Expansion"
        - "Q3 2024: Enterprise Features"
        - "Q4 2024: Community & Scale"
    validations:
      required: true
