name: 📊 Integration Enhancement
description: Propose enhancements to an existing integration
title: "📊 Integration: [Service Name] Enhancement - [Feature]"
labels: ["integration: improvement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose an integration enhancement!

  - type: input
    id: integration-name
    attributes:
      label: Integration Name
      description: Which integration needs enhancement?
      placeholder: "e.g., Stripe"
    validations:
      required: true

  - type: input
    id: feature-name
    attributes:
      label: Enhancement Name
      description: What is the name of this enhancement?
      placeholder: "e.g., Subscription Management"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the enhancement and its purpose
      placeholder: "e.g., Add comprehensive subscription management capabilities to the Stripe integration"
    validations:
      required: true

  - type: textarea
    id: features
    attributes:
      label: Features to Add
      description: List the specific features or improvements
      placeholder: |
        - Subscription creation and management
        - Invoice customization
        - Webhook handling
        - Usage tracking
    validations:
      required: true

  - type: textarea
    id: technical-requirements
    attributes:
      label: Technical Requirements
      description: List the technical requirements for this enhancement
      value: |
        - Maintain async patterns
        - Add new type definitions
        - Expand test coverage
        - Update documentation
    validations:
      required: true

  - type: textarea
    id: success-criteria
    attributes:
      label: Success Criteria
      description: What defines this enhancement as complete?
      value: |
        - All planned features implemented
        - Tests covering new functionality
        - Documentation updated
        - Example code added
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What is the priority level for this enhancement?
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: dropdown
    id: milestone
    attributes:
      label: Target Milestone
      description: When should this enhancement be completed?
      options:
        - "Q1 2024: Foundation"
        - "Q2 2024: Expansion"
        - "Q3 2024: Enterprise Features"
        - "Q4 2024: Community & Scale"
    validations:
      required: true
