name: 🛠️ Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Compile new requirements
        run: pip-compile --upgrade

      - name: Check for changes
        id: git_diff
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git diff > diff.txt
          if [ -s diff.txt ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if dependencies updated
        if: steps.git_diff.outputs.changes == 'true'
        run: |
          git add requirements.txt
          git commit -m "chore: update dependencies to latest versions"
          git push
        env:
          GIT_TOKEN: ${{ secrets.GH_PAT }}
